spring:
  jpa:
    show-sql: false
  flyway:
    clean-disabled: true

server:
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    root: INFO
    com.sogeco: INFO
  pattern:
    console: '{"ts":"%d{ISO8601}","level":"%level","trace":"%X{traceId}","logger":"%logger{36}","msg":"%replace(%msg){"\"","'"'"'"}"}%n'
